import Head from "next/head";
import styles from "@/styles/neumorphic.module.css"
import Link from "next/link";
import Navbar from "@/components/navbar";

export default function Profile() {
    return (
        <>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <style>

                </style>
            </Head>

            <Navbar></Navbar>
            <div className="flex w-full flex-col">
                <div className="flex-1 flex items-center justify-center bg-black">
                    <div className="w-full lg:w-2/3 w-full shadow-md h-screen mt-4">
                        {/* Profile Image */}
                        <div className=" justify-center">
                            <div className="w-1/2 lg:w-1/5 md:w-1/4 border-8 border-green-500  mx-auto rounded-full overflow-hidden">
                                <img src="/profile.webp" className="object-cover" />
                            </div>
                        </div>

                        <div className="border border-zinc-900 shadow-md shadow-zinc-900 rounded-lg bg-zinc-900 p-4 m-4">
                            <div className="flex w-full flex-row">
                            <div className="flex flex-col items-center justify-center items-center w-1/2">
                                <span className="mx-auto text-xl">Follower</span>
                                <span className="text font-bold text-xl">200</span>
                            </div>
                            <div className="flex flex-col items-center justify-center items-center w-1/2">
                                <span className="mx-auto text-xl">Following</span>
                                <span className="text font-bold text-xl">140</span>
                            </div>
                            </div>
                        </div>

                        
                    </div>
                </div>
            </div>

        </>
    );
}
