import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Register() {
    const defaultFormData = {
      username: "",
      email: "",
      password: ""
    }
    const [formData, setFormData] = useState({...defaultFormData});
    const [errorMessage, setErrorMessage] = useState("");
    const [successMessage, setSuccessMessage] = useState("");

    const resetMessage = async () =>{
      setErrorMessage("");
      setSuccessMessage("");
    }

    const handleInputChange = (e) => {
      const { name, value } = e.target;
      setFormData((prevData) => ({
          ...prevData,
          [name]: value
      }));
    };

    const handleSubmit = async (event) => {
        event.preventDefault();
        await resetMessage();

        try {
            const response = await fetch('/api/register', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(formData), // Use formData object here
            });

            if (response.ok) {
                // Handle successful registration
                setSuccessMessage("Registration successful");
                setFormData({...defaultFormData});
            } else {
                // Handle errors
                const data = await response.json();
                setErrorMessage(data.message || "Registration failed");
            }
        } catch (error) {
            console.log(error.message);
            console.log(error);
            setErrorMessage("An error occurred during registration");
        }
    };

    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/web_logo.png" />
            </Head>

            <div className="flex w-full lg:h-screen flex-col lg:flex-row">
                {/* Left Side - Logo */}
                <div className="md:flex md:flex-1 items-center justify-center bg-black">
                    <img src="/io.png" alt="Logo" className="lg:w-1/2 w-1/4 rounded-[80px] mt-20 mx-auto h-auto"/>
                </div>

                {/* Right Side - Form */}
                <div className="flex-1 flex items-center justify-center bg-black">
                    <div className="w-full max-w-md p-6 shadow-md">
                        <h2 className="text-2xl font-semibold mb-6 text-white">Register</h2>
                        <form onSubmit={handleSubmit}>
                            <div className="mb-4">
                                <label htmlFor="username" className="block text-white font-medium mb-2">Username</label>
                                <input 
                                    type="text" 
                                    name="username" 
                                    id="username" 
                                    className="input input-bordered rounded-full w-full" 
                                    placeholder="Enter your username"
                                    value={formData.username}
                                    onChange={handleInputChange}
                                />
                            </div>
                            <div className="mb-4">
                                <label htmlFor="email" className="block text-white font-medium mb-2">Email</label>
                                <input 
                                    type="email" 
                                    name="email" 
                                    id="email" 
                                    className="input input-bordered rounded-full w-full" 
                                    placeholder="Enter your email"
                                    value={formData.email}
                                    onChange={handleInputChange}
                                />
                            </div>
                            <div className="mb-6">
                                <label htmlFor="password" className="block text-white font-medium mb-2">Password</label>
                                <input 
                                    type="password" 
                                    name="password" 
                                    id="password" 
                                    className="input input-bordered rounded-full w-full" 
                                    placeholder="Enter your password"
                                    value={formData.password}
                                    onChange={handleInputChange}
                                />
                            </div>
                            {successMessage && <p className="text-green-500 text-center my-2">{successMessage}</p>}
                            {errorMessage && <p className="text-red-500 text-center my-2">{errorMessage}</p>}
                            <div className="flex items-center justify-between">
                                <button type="submit" className="btn rounded-full w-full bg-gradient-to-r from-pink-500 to-yellow-500 text-white hover:from-green-500 hover:to-sky-500">Register</button>
                            </div>
                            <div className="flex items-center justify-center pt-2">
                                <span className="text-white">Already have an account? <Link href={"/login"} className="text-extrabold bg-gradient-to-r from-pink-500 to-yellow-500 inline-block text-transparent bg-clip-text hover:from-green-500 hover:to-sky-500">Login Here</Link> </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </>
    );
}
